### ISSUE TITLE
List Products

### ISSUE THREAD

**Issue by JShimota** [NYU-DevOps-Class-Product-Squad/products#10]
**As an** User  
 **I need** to discover all products  
 **So that** I can see what products are sold 

### Details and Assumptions
 * the website sells products
 * the list is open to any users (no need to log in or create account)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I am interested in the company's products
 When want to see the products 
 Then all the products display

**Comment by kesarkeri** [comment]
This looks good!
