### ISSUE TITLE
Create database model and schema

### ISSUE THREAD

**Issue by kesarkeri** [NYU-DevOps-Class-Product-Squad/products#3]
**As a** database engineer
 **I need** to create database model and schema  
 **So that** I can create a database of products

### Details and Assumptions
 * There are multiple products 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are products 
 When a product needs to be added to the database
 Then there is a correct field for all the attributes and it can be saved to the database

**Comment by JShimota** [comment]
Do we need a flag to indicate whether an item is in stock or for sale?
