### ISSUE TITLE
Create a Python Flask Cloud Foundry

### ISSUE THREAD

**Issue by kesarkeri** [NYU-DevOps-Class-Product-Squad/products#49]
**As a** developer
 **I need** to setup a python environment
 **So that** I can run my python file

### DETAILS:
 * Create a Python Flask Cloud Foundry application in IBM Cloud - US South
 * Naming is very important so please follow the following format: Use the singular version of your resource name (e.g., orders becomes order) prefixed by nyu- and suffixed by -service-sp2201. For example: if you are creating the /orders API then please name your IBM Cloud service nyu-order-service-sp2201 (The full URL will then be nyu-order-service-sp2201.ussouth.cf.appdomain.cloud )
 
   
 ### Acceptance Criteria  
 * region is set to US South
 * naming convention is followed - uses the singular version of your resource name (e.g., orders becomes order) prefixed by nyu- and suffixed by -service-sp2201
 
 ```gherkin
 Given IBM cloud account is setup
 When Flask app is deployed in python environment
 Then it runs python files

**Comment by jsimms-nyu** [comment]
@JShimota i created a python flask in ibm following the class slides and then think i linked this to elephantsql - i put the screen shot that i think shows this in our slack. i THINK...
