### ISSUE TITLE
Delete Product

### ISSUE THREAD

**Issue by JShimota** [NYU-DevOps-Class-Product-Squad/products#8]
**As an** inventory manager 
 **I need** to delete products 
 **So that** I can delete products we no want to longer sell

**As a** marketing manager 
 **I need** to delete products 
 **So that** I can restrict availability or visibility of a product 

### Details and Assumptions
 * The product already exists in the database 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a product needs to be deleted 
 When delete the product
 Then it is removed from the database

**Comment by jsimms-nyu** [comment]
Might we perhaps also need the ability to retrieve the delete product's information? We should also ensure that there is a way to double check that the user does definitely want to delete the product to reduce the risk of someone accidentally deleting a product.
